spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:userdb}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_URL:http://localhost:8180}/realms/${KEYCLOAK_REALM:my-realm}/protocol/openid-connect/certs
          issuer-uri: ${KEYCLOAK_URL:http://localhost:8180}/realms/${KEYCLOAK_REALM:my-realm}

server:
  port: 8081

keycloak:
  realm: ${KEYCLOAK_REALM:my-realm}
  auth-server-url: ${KEYCLOAK_URL:http://localhost:8180}
  ssl-required: external
  resource: ${KEYCLOAK_CLIENT_ID:frontend-client}
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET:tAKQOiyVMqyuHGejz8zIAoYVzHnR5DI1}
  use-resource-role-mappings: true
  bearer-only: true

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.hibernate: INFO
    com.imobiliaria: DEBUG  # mantém debug apenas para seu código
    org.hibernate.SQL: DEBUG  # mantém queries SQL visíveis
    org.hibernate.type.descriptor.sql: TRACE  # mostra valores dos parâmetros
