export enum Feature {
  POOL = "POOL",
  GYM = "GYM",
  GARAGE = "GARAGE",
  GARDEN = "GARDEN",
  SECURITY = "SECURITY",
  BALCONY = "BALCONY",
  FURNISHED = "FURNISHED",
  AIR_CONDITIONING = "AIR_CONDITIONING",
  ELEVATOR = "ELEVATOR",
  GOURMET_AREA = "GOURMET_AREA",
  PLAYGROUND = "PLAYGROUND",
  PARTY_ROOM = "PARTY_ROOM",
  LAUNDRY = "LAUNDRY",
  PET_FRIENDLY = "PET_FRIENDLY"
}

