spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

server:
  port: 8081

---
#spring:
#  config:
#    activate:
#      on-profile: prod
#  datasource:
#    url: ${SPRING_DATASOURCE_URL}
#    username: ${SPRING_DATASOURCE_USERNAME}
#    password: ${SPRING_DATASOURCE_PASSWORD}
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#
#server:
#  port: ${PORT:8081}spring:
#  profiles:
#    active: ${SPRING_PROFILES_ACTIVE:dev}
#
#---
#spring:
#  config:
#    activate:
#      on-profile: dev
#  datasource:
#    url: jdbc:postgresql://localhost:5432/userdb
#    username: postgres
#    password: postgres
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://minimalestate.local/auth/realms/my-realm
#
#server:
#  port: 8081
#
#---
#spring:
#  config:
#    activate:
#      on-profile: prod
#  datasource:
#    url: ${SPRING_DATASOURCE_URL}
#    username: ${SPRING_DATASOURCE_USERNAME}
#    password: ${SPRING_DATASOURCE_PASSWORD}
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: ${KEYCLOAK_URL}/realms/my-realm

server:
  port: ${PORT:8081}